project:
  type: website


website:
  title: "MixtureExperiemnts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - objectives.qmd
      - MixtureDesigns.qmd
      - TriangularCoordinateSystems.qmd
      - TheSimplexCentroid.qmd
      - TheSimplexAugmentedDesign.qmd
      - L-SimplexExtremeVertices.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

